apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'python-app'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['pythonsvc.default.svc.cluster.local:5000']
