apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx

  rules:
    - host: "python.arunm.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pythonsvc
                port:
                  number: 5000

    - host: "prometheus.arunm.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090

    - host: "grafana.arunm.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-svc
                port:
                  number: 3000
